/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pelanggan;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import server.helperClass;
import server.mysql;

/**
 *
 * @author DELL
 */
public class viewOrder extends javax.swing.JFrame {
    private mysql db;
    private Statement stm;
    private ResultSet res;
    private int orderID;
    int dragxmouse;
    int dragymouse;
    /**
     * Creates new form lihatOrder
     * @param orderID
     */
    public viewOrder(int orderID) throws SQLException {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        this.db = new mysql();
        this.stm = mysql.getConnection().createStatement();
        
        String ordID;
        if(orderID == 0) {
            ordID = "{{restrictedAccess}}";
        }
        else {
            String getData = "SELECT orderNumber FROM orders WHERE orderID = '"+ orderID +"'";
            this.res = this.stm.executeQuery(getData);
            if(this.res.next()) {
                ordID = this.res.getString("orderNumber");
                this.fillData(orderID);
                this.orderID = orderID;
            }
            else {
                ordID = "{{failedToCallDatabase}}";
            }
        }
        
        setTitle("ORDER #"+ ordID);
        setPreferredSize(new Dimension(5000, 800));
        setResizable(false);
        setLocationRelativeTo(null);
        
        orderTitle.setText("Order #"+ ordID);
        
        pack();
    }
    
    private void fillData(int ID) {
        try {
            DefaultTableModel model = (DefaultTableModel) orderItems.getModel();

            String getOrderData = "SELECT * FROM `orders` WHERE `orderID` = '" + ID + "'";
            this.res = this.stm.executeQuery(getOrderData);
           if (this.res.next()) {
                String num = this.res.getString("orderNumber");
                String date = this.res.getString("orderTime");
                String qty = this.res.getString("orderQuantity");
                Double price = this.res.getDouble("totalPrice");
                boolean status = this.res.getBoolean("status");
                boolean paid = this.res.getBoolean("isPaid");

                String totalHarga = helperClass.formatRupiah(price);
                
                String ordStatus = (status) ? "Selesai" : "Proses";
                String paidStatus = (paid) ? "Sudah dibayar" : "Belum dibayar";
                
                orderStatus.setText(ordStatus);
                payStatus.setText(paidStatus);
                orderPrice.setText(totalHarga);
                orderQty.setText(qty);
            }

            String getItems = "SELECT o.orderID, f.name, i.foodID, i.orderQuantity as qty, i.priceEach as price FROM orders o JOIN orderItems i ON i.orderID = o.orderID JOIN foods f ON f.foodID = i.foodID WHERE o.orderID = '" + ID + "'";
            this.res = this.stm.executeQuery(getItems);

            if (this.res.next()) {
                do {
                    int foodID = this.res.getInt("foodID");
                    String nama = this.res.getString("name");
                    int qty = this.res.getInt("qty");
                    Double price = this.res.getDouble("price");
                    Double subtotal = (price * qty);

                    model.addRow(new Object[]{foodID, nama, helperClass.formatRupiah(price), qty, helperClass.formatRupiah(subtotal)});
                } while (this.res.next());
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listOrder = new javax.swing.JLabel();
        orderTitle = new javax.swing.JLabel();
        orderPrice = new javax.swing.JTextField();
        orderQty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        payPanel = new javax.swing.JScrollPane();
        orderItems = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        orderStatus = new javax.swing.JLabel();
        payStatus = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        backLink = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        onsreen = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/image/list.png"))); // NOI18N
        listOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listOrderMouseClicked(evt);
            }
        });
        getContentPane().add(listOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 40, 40));

        orderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        orderTitle.setForeground(new java.awt.Color(255, 149, 0));
        orderTitle.setText("Order #AA0000");
        getContentPane().add(orderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        orderPrice.setEditable(false);
        getContentPane().add(orderPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 100, -1));

        orderQty.setEditable(false);
        getContentPane().add(orderQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, 90, -1));

        jLabel1.setForeground(new java.awt.Color(255, 149, 0));
        jLabel1.setText("Jumlah:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, -1, 20));

        orderItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Harga satuan", "Jumlah beli", "Total harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        payPanel.setViewportView(orderItems);

        getContentPane().add(payPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 800, 220));

        jLabel5.setForeground(new java.awt.Color(255, 149, 0));
        jLabel5.setText("Status proses");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 149, 0));
        jLabel6.setText("Status bayar ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        orderStatus.setForeground(new java.awt.Color(255, 255, 255));
        orderStatus.setText("false");
        getContentPane().add(orderStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        payStatus.setForeground(new java.awt.Color(255, 255, 255));
        payStatus.setText("false");
        getContentPane().add(payStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        payBtn.setText("BAYAR");
        payBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });
        getContentPane().add(payBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, -1, -1));

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/image/icons8-remove-64.png"))); // NOI18N
        delBtn.setBorderPainted(false);
        delBtn.setContentAreaFilled(false);
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        getContentPane().add(delBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 690, -1, -1));

        backLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/image/backk.png"))); // NOI18N
        backLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLinkMouseClicked(evt);
            }
        });
        getContentPane().add(backLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/image/garis.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        onsreen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                onsreenMouseDragged(evt);
            }
        });
        onsreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onsreenMousePressed(evt);
            }
        });
        getContentPane().add(onsreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 770));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/image/data order.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listOrderMouseClicked
        try {
            new orderLists().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(viewOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listOrderMouseClicked

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        int ID = this.orderID;
        
        if(ID > 0) {
            int doPay = JOptionPane.showConfirmDialog(payPanel, (Object) "Tandai order ini sebagai sudah dibayar?", "Bayar order", 0);
            if (doPay == 0) {
                try {
                    String pay = "UPDATE `orders` SET `isPaid` = '1' WHERE `orderID` = '" + ID + "'";
                    int bayar = this.stm.executeUpdate(pay);
                    if (bayar > 0) {
                        JOptionPane.showMessageDialog(payPanel, "Order dibayar!");
                        payBtn.setVisible(false);
                        payStatus.setText("Sudah dibayar");
                    }
                    else {
                         JOptionPane.showMessageDialog(payPanel, "Terjadi kesalahan. Harap ulangi kembali.");
                    }
                }
                catch (SQLException ex) {
                    Logger.getLogger(orderLists.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else {
             JOptionPane.showMessageDialog(payPanel, "Tidak ada order");
        }
    }//GEN-LAST:event_payBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        int ID = this.orderID;
        
        if(ID > 0) {
            int doHapus = JOptionPane.showConfirmDialog(payPanel, (Object) "Yakin ingin menghapus order ini?", "Hapus Order", 0);
            if (doHapus == 0) {
                try {
                    String delete = "DELETE FROM `orders` WHERE `orderID` = '" + ID + "'";
                    int hapus = this.stm.executeUpdate(delete);
                    int hps = this.stm.executeUpdate("DELETE FROM `orderItems` WHERE `orderID` = '" + ID + "'");
                    if (hapus > 0 && hps > 0) {
                        JOptionPane.showMessageDialog(payPanel, "Order berhasil dihapus!");
                        new orderLists().setVisible(true);
                        this.dispose();
                    }
                    else {
                        JOptionPane.showMessageDialog(payPanel, "Gagal menghapus order");
                    }
                }
                catch (SQLException ex) {
                    Logger.getLogger(orderLists.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(payPanel, "Tidak ada order!");
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void onsreenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onsreenMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - dragxmouse,y-dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_onsreenMouseDragged

    private void onsreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onsreenMousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_onsreenMousePressed

    private void backLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLinkMouseClicked
        try {
            new createOrder().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(viewOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_backLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new viewOrder(0).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(viewOrder.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLink;
    private javax.swing.JLabel bg;
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel listOrder;
    private javax.swing.JLabel onsreen;
    private javax.swing.JTable orderItems;
    private javax.swing.JTextField orderPrice;
    private javax.swing.JTextField orderQty;
    private javax.swing.JLabel orderStatus;
    private javax.swing.JLabel orderTitle;
    private javax.swing.JButton payBtn;
    private javax.swing.JScrollPane payPanel;
    private javax.swing.JLabel payStatus;
    // End of variables declaration//GEN-END:variables
}
