/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author masrc
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    int dragxmouse;
    int dragymouse;
    public admin() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userbtn = new javax.swing.JButton();
        menubtn = new javax.swing.JButton();
        pilihanbtn = new javax.swing.JButton();
        status = new javax.swing.JButton();
        onscreen = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        userbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/userbtn1.png"))); // NOI18N
        userbtn.setBorderPainted(false);
        userbtn.setContentAreaFilled(false);
        userbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userbtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userbtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userbtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userbtnMouseEntered(evt);
            }
        });
        getContentPane().add(userbtn);
        userbtn.setBounds(20, 110, 270, 80);

        menubtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/menubtn1.png"))); // NOI18N
        menubtn.setBorderPainted(false);
        menubtn.setContentAreaFilled(false);
        menubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menubtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menubtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menubtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menubtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menubtnMouseEntered(evt);
            }
        });
        menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubtnActionPerformed(evt);
            }
        });
        getContentPane().add(menubtn);
        menubtn.setBounds(20, 180, 270, 80);

        pilihanbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/pilihanbtn1.png"))); // NOI18N
        pilihanbtn.setBorderPainted(false);
        pilihanbtn.setContentAreaFilled(false);
        pilihanbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pilihanbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pilihanbtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilihanbtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pilihanbtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pilihanbtnMouseEntered(evt);
            }
        });
        getContentPane().add(pilihanbtn);
        pilihanbtn.setBounds(20, 250, 270, 80);

        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/status1.png"))); // NOI18N
        status.setBorderPainted(false);
        status.setContentAreaFilled(false);
        status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                statusMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statusMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statusMouseEntered(evt);
            }
        });
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status);
        status.setBounds(20, 330, 270, 69);

        onscreen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                onscreenMouseDragged(evt);
            }
        });
        onscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onscreenMousePressed(evt);
            }
        });
        getContentPane().add(onscreen);
        onscreen.setBounds(20, 20, 1170, 780);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/admin.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(20, 10, 1200, 800);

        setSize(new java.awt.Dimension(1279, 825));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onscreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onscreenMousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_onscreenMousePressed

    private void onscreenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onscreenMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse,y-dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_onscreenMouseDragged

    private void userbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/userbtn2.png"));
        userbtn.setIcon(b);                                 
    }//GEN-LAST:event_userbtnMouseEntered

    private void userbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/userbtn1.png"));
        userbtn.setIcon(b);   
    }//GEN-LAST:event_userbtnMouseExited

    private void userbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/userbtn1.png"));
        userbtn.setIcon(b);   
    }//GEN-LAST:event_userbtnMousePressed

    private void userbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/userbtn2.png"));
        userbtn.setIcon(b);   
    }//GEN-LAST:event_userbtnMouseReleased

    private void menubtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/menubtn2.png"));
        menubtn.setIcon(b);   
    }//GEN-LAST:event_menubtnMouseEntered

    private void menubtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/menubtn1.png"));
        menubtn.setIcon(b);  
    }//GEN-LAST:event_menubtnMouseExited

    private void menubtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/menubtn1.png"));
        menubtn.setIcon(b);  
    }//GEN-LAST:event_menubtnMousePressed

    private void menubtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/menubtn2.png"));
        menubtn.setIcon(b);  
    }//GEN-LAST:event_menubtnMouseReleased

    private void pilihanbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanbtnMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/pilihanbtn2.png"));
        pilihanbtn.setIcon(b);  
    }//GEN-LAST:event_pilihanbtnMouseEntered

    private void pilihanbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanbtnMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/pilihanbtn1.png"));
        pilihanbtn.setIcon(b);  
    }//GEN-LAST:event_pilihanbtnMouseExited

    private void pilihanbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanbtnMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/pilihanbtn1.png"));
        pilihanbtn.setIcon(b);  
    }//GEN-LAST:event_pilihanbtnMousePressed

    private void pilihanbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanbtnMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/pilihanbtn2.png"));
        pilihanbtn.setIcon(b);  
    }//GEN-LAST:event_pilihanbtnMouseReleased

    private void menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubtnActionPerformed

    }//GEN-LAST:event_menubtnActionPerformed

    private void menubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseClicked
        try {
            new menu().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menubtnMouseClicked

    private void userbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseClicked
        try {
            new datausers().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_userbtnMouseClicked

    private void pilihanbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanbtnMouseClicked
        try {
            new pilihan().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pilihanbtnMouseClicked

    private void statusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/status1.png"));
        status.setIcon(b);
    }//GEN-LAST:event_statusMousePressed

    private void statusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/status2.png"));
        status.setIcon(b);
    }//GEN-LAST:event_statusMouseReleased

    private void statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseClicked
        try {
            new daftarPesanan().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_statusMouseClicked

    private void statusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/status1.png"));
        status.setIcon(b);
    }//GEN-LAST:event_statusMouseExited

    private void statusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/status2.png"));
        status.setIcon(b);
    }//GEN-LAST:event_statusMouseEntered

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton menubtn;
    private javax.swing.JLabel onscreen;
    private javax.swing.JButton pilihanbtn;
    private javax.swing.JButton status;
    private javax.swing.JButton userbtn;
    // End of variables declaration//GEN-END:variables
}
