/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import server.helperClass;
import server.mysql;

/**
 *
 * @author DELL
 */
public class datausers extends javax.swing.JFrame {
    private HashMap<Object, Integer> userGrant;
    private final mysql db;
    private final Statement stm;
    private ResultSet res;
    private boolean  doEdit = false;
    int dragxmouse;
    int dragymouse;
    /**
     * Creates new form addMenu
     *
     * @throws java.sql.SQLException
     */
    public datausers() throws SQLException {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        this.userGrant = new HashMap<Object, Integer>();
        this.userGrant.put("Kasir", 2);
        this.userGrant.put("Dapur", 3);
        
        this.db = new mysql();
        this.stm = mysql.getConnection().createStatement();

        setTitle("KELOLA USER");
        setPreferredSize(new Dimension(5000, 800));
        setResizable(false);
        setLocationRelativeTo(null);
 
        this.fillUserList();

        headerTitle.setVisible(false);
        nameAlert.setVisible(false);
        hpMsg.setVisible(false);
        editBtn.setVisible(false);
        delBtn.setVisible(false);
        editID.setVisible(false);
        usernameAlert.setVisible(false);
        passwordALert.setVisible(false);
        
        pack();
    }

    private void fillUserList() {
        try {
            DefaultTableModel list = (DefaultTableModel) userList.getModel();

            String getMenuList = "SELECT u.*, p.* FROM `users` `u` JOIN `userProfile` `p` ON u.userID = p.userID WHERE `userGrant` != '1'";
            this.res = this.stm.executeQuery(getMenuList);

            if (this.res.next()) {
                do {
                    int ID = this.res.getInt("userID");
                    String nama = this.res.getString("fullName");
                    String user = this.res.getString("username");
                    String hp = this.res.getString("phoneNumber");
                    int grant = this.res.getInt("userGrant");
                    String userGrant = (grant == 2) ? "Kasir" : "Dapur";

                    list.addRow(new Object[]{ID, user, nama, hp, userGrant});
                } while (this.res.next());
            }
        } catch (SQLException ex) {
            Logger.getLogger(datausers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateTable() {
        try {
            DefaultTableModel list = (DefaultTableModel) userList.getModel();
            list.setRowCount(0);

            String getUsers = "SELECT u.*, p.* FROM `users` `u` JOIN `userProfile` `p` ON u.userID = p.userID WHERE `userGrant` != '1'";
            this.res = this.stm.executeQuery(getUsers);

            if (this.res.next()) {
                do {
                    int ID = this.res.getInt("userID");
                    String user = this.res.getString("username");
                    String nama = this.res.getString("fullName");
                    String hp = this.res.getString("phoneNumber");
                    int grant = this.res.getInt("userGrant");
                    String userGrant = (grant == 2) ? "Kasir" : "Dapur";

                    list.addRow(new Object[]{ID, user, nama, hp, userGrant});
                } while (this.res.next());
            }
        } catch (SQLException ex) {
            Logger.getLogger(datausers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JScrollPane();
        userList = new javax.swing.JTable();
        editID = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        nameAlert = new javax.swing.JLabel();
        inputHP = new javax.swing.JTextField();
        hpMsg = new javax.swing.JLabel();
        usernameAlert = new javax.swing.JLabel();
        passwordALert = new javax.swing.JLabel();
        headerTitle = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        userbtn = new javax.swing.JButton();
        menubtn = new javax.swing.JButton();
        pilihanbtn = new javax.swing.JButton();
        status = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        selectGrant = new javax.swing.JComboBox();
        editPanel = new javax.swing.JLabel();
        onsreen = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Nama", "No. HP", "Hak Akses"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userListMouseClicked(evt);
            }
        });
        menuPanel.setViewportView(userList);
        if (userList.getColumnModel().getColumnCount() > 0) {
            userList.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 560, 410));

        editID.setText("{{editID}}");
        getContentPane().add(editID, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 300, -1, -1));
        getContentPane().add(inputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 220, -1));

        nameAlert.setText("{{namaMsg}}");
        getContentPane().add(nameAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 320, -1, -1));

        inputHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHPActionPerformed(evt);
            }
        });
        getContentPane().add(inputHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, 220, -1));

        hpMsg.setText("{{hpAlert}}");
        getContentPane().add(hpMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 390, -1, -1));

        usernameAlert.setText("{{usernameAlert}}");
        getContentPane().add(usernameAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 500, -1, 20));

        passwordALert.setText("{{passwordField}}");
        getContentPane().add(passwordALert, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 570, -1, -1));

        headerTitle.setText("{{msg}}");
        getContentPane().add(headerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, -1, -1));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/tambahuser1.png"))); // NOI18N
        addBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addBtn.setBorderPainted(false);
        addBtn.setContentAreaFilled(false);
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addBtnMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 620, 190, 50));

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/edituser1.png"))); // NOI18N
        editBtn.setBorderPainted(false);
        editBtn.setContentAreaFilled(false);
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editBtnMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editBtnMouseEntered(evt);
            }
        });
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 670, -1, -1));

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/deleteuser1.png"))); // NOI18N
        delBtn.setBorderPainted(false);
        delBtn.setContentAreaFilled(false);
        delBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                delBtnMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delBtnMouseEntered(evt);
            }
        });
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        getContentPane().add(delBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 670, -1, -1));

        userbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/userbtn1.png"))); // NOI18N
        userbtn.setBorderPainted(false);
        userbtn.setContentAreaFilled(false);
        userbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userbtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userbtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userbtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userbtnMouseEntered(evt);
            }
        });
        getContentPane().add(userbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 270, -1));

        menubtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/menubtn1.png"))); // NOI18N
        menubtn.setBorderPainted(false);
        menubtn.setContentAreaFilled(false);
        menubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menubtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menubtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menubtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menubtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menubtnMouseEntered(evt);
            }
        });
        menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubtnActionPerformed(evt);
            }
        });
        getContentPane().add(menubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 270, -1));

        pilihanbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/pilihanbtn1.png"))); // NOI18N
        pilihanbtn.setBorderPainted(false);
        pilihanbtn.setContentAreaFilled(false);
        pilihanbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pilihanbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pilihanbtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilihanbtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pilihanbtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pilihanbtnMouseEntered(evt);
            }
        });
        getContentPane().add(pilihanbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 270, -1));

        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/status1.png"))); // NOI18N
        status.setBorderPainted(false);
        status.setContentAreaFilled(false);
        status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                statusMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statusMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statusMouseEntered(evt);
            }
        });
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 270, -1));

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, 230, 25));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 590, 230, 25));

        selectGrant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kasir", "Dapur" }));
        selectGrant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectGrantActionPerformed(evt);
            }
        });
        getContentPane().add(selectGrant, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, 220, -1));

        editPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/form.png"))); // NOI18N
        getContentPane().add(editPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, -1, -1));

        onsreen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                onsreenMouseDragged(evt);
            }
        });
        onsreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onsreenMousePressed(evt);
            }
        });
        getContentPane().add(onsreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1170, 780));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/images/adminuser.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1280, -1));

        setSize(new java.awt.Dimension(1329, 814));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if(this.doEdit) {
            inputNama.setText("");
            inputHP.setText("");
            editID.setText("");
            usernameField.setText("");
            usernameField.setText("");
            passwordField.setText("");
            selectGrant.setSelectedIndex(0);
            addBtn.setText("");
            
            editBtn.setVisible(false);
            delBtn.setVisible(false);
            
            this.doEdit = false;
        }
        else {
        try {
            String nama = inputNama.getText();
            String hp = inputHP.getText();
            String username = usernameField.getText();
            String password = passwordField.getText();
            Object grant = selectGrant.getSelectedItem();
            Integer userGrant = this.userGrant.get((String) grant);

            if (nama.equals("")) {
                inputNama.requestFocus();
                nameAlert.setText("Masukkan nama user!");
                nameAlert.setVisible(true);
            }
            else {
                nameAlert.setVisible(false);
            }
            if (hp.equals("")) {
                inputHP.requestFocus();
                hpMsg.setText("Masukkan No. HP user!");
                hpMsg.setVisible(true);
            }
            else {
                hpMsg.setVisible(false);
            }
            if(username.equals("")) {
                usernameField.requestFocus();
                usernameAlert.setText("Masukkan username!");
                usernameAlert.setVisible(true);
            }
            else {
                usernameAlert.setVisible(false);
            }
            if(password.equals("")) {
                passwordALert.setText("Masukkan password!");
                passwordALert.setVisible(true);
            }
            else {
                passwordALert.setVisible(false);
            }

            if (!nama.equals("") && !hp.equals("") && !username.equals("") && !password.equals("")) {
                String cekUsername = "SELECT * FROM users WHERE username = '"+ username +"'";
                this.res = this.stm.executeQuery(cekUsername);
                
                if(this.res.next()) {
                    usernameAlert.setText("Username "+ username +" sudah terdaftar!");
                    usernameAlert.setVisible(true);
                }
                else {
                    usernameAlert.setVisible(false);
                    
                    String pass = helperClass.getMD5(password);
                    String insertUser = "INSERT INTO `users` VALUES (NULL, '"+ username +"', '"+ pass +"', '"+ userGrant +"')";
                    PreparedStatement pstmt = mysql.getConnection().prepareStatement(insertUser, Statement.RETURN_GENERATED_KEYS);
                    int insert = pstmt.executeUpdate();

                    ResultSet gK = pstmt.getGeneratedKeys();
                    if(gK.next()) {
                        int userID = gK.getInt(1);
                        
                        String insertProfile = "INSERT INTO userProfile VALUES (NULL, '"+ userID +"', '"+ nama +"', '"+ hp +"')";
                        int Insert = this.stm.executeUpdate(insertProfile);
                        if(Insert > 0) {
                            this.updateTable();
                            
                            headerTitle.setText("User baru berhasil ditambahkan");
                            headerTitle.setVisible(true);
                            
                            inputNama.setText("");
                            inputHP.setText("");
                            usernameField.setText("");
                            passwordField.setText("");
                        }
                        
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(datausers.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void userListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListMouseClicked
        try {
            this.doEdit = true;
            DefaultTableModel list = (DefaultTableModel) userList.getModel();
            int sel = userList.getSelectedRow();
            String id = list.getValueAt(sel, 0).toString();
            int ID = Integer.parseInt(id);

            addBtn.setText("");
            editBtn.setVisible(true);
            delBtn.setVisible(true);

            String getData = "SELECT u.*, p.* FROM `users` `u` JOIN `userProfile` `p` ON u.userID = p.userID WHERE `userGrant` != '1' AND u.userID = '"+ ID +"'";
            this.res = this.stm.executeQuery(getData);
            if (this.res.next()) {
                int userID = this.res.getInt("userID");
                String user = this.res.getString("username");
                String nama = this.res.getString("fullName");
                String hp = this.res.getString("phoneNumber");
                int grant = this.res.getInt("userGrant");
                String userGrant = (grant == 2) ? "Kasir" : "Dapur";

                inputNama.setText(nama);
                inputHP.setText(hp);
                editID.setText(String.valueOf(userID));
                usernameField.setText(user);

                selectGrant.setSelectedItem(userGrant);
            }
        } catch (SQLException ex) {
            Logger.getLogger(datausers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_userListMouseClicked

    private void inputHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHPActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        DefaultTableModel list = (DefaultTableModel) userList.getModel();
        int doHapus = JOptionPane.showConfirmDialog(editPanel, (Object) "Yakin ingin menghapus user ini?", "Hapus user", 0);
        String userID = editID.getText();

        if (doHapus == 0) {
            try {
                String ID = editID.getText();
                String Hapus = "DELETE FROM `users` WHERE `userID` = '" + userID + "'";
                int hapus = this.stm.executeUpdate(Hapus);
                int hapusProfile = this.stm.executeUpdate("DELETE FROM `userProfile` WHERE `userID` = '"+ userID +"'");

                if (hapus > 0 && hapusProfile > 0) {
                    headerTitle.setText("User berhasil dihapus");
                    headerTitle.setVisible(true);

                    inputHP.setText("");
                    inputNama.setText("");
                    selectGrant.setSelectedIndex(0);

                    this.updateTable();
                    addBtn.setVisible(true);
                    delBtn.setVisible(false);
                    editBtn.setVisible(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(datausers.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        try {
            String uID = editID.getText();
            String nama = inputNama.getText();
            String hp = inputHP.getText();
            String username = usernameField.getText();
            String password = passwordField.getText();
            Object grant = selectGrant.getSelectedItem();
            Integer userGrant = this.userGrant.get((String) grant);

            if (nama.equals("")) {
                inputNama.requestFocus();
                nameAlert.setText("Masukkan nama user!");
                nameAlert.setVisible(true);
            }
            else {
                nameAlert.setVisible(false);
            }
            if (hp.equals("")) {
                inputHP.requestFocus();
                hpMsg.setText("Masukkan No. HP user!");
                hpMsg.setVisible(true);
            }
            else {
                hpMsg.setVisible(false);
            }
            
            if (!nama.equals("") && !hp.equals("")) {
                String updateProfile = "UPDATE `userProfile` SET `fullName` = '"+ nama +"', `phoneNumber` = '"+ hp +"' WHERE `userID` = '"+ uID +"'";
                int updateUserProfile = this.stm.executeUpdate(updateProfile);
                int updateUserName = 0;
                int updateUserPassword = 0;
                
                if( ! username.equals("")) {
                    updateUserName = this.stm.executeUpdate("UPDATE `users` SET `username` = '"+ username +"' WHERE `userID` = '"+ uID +"'");
                }
                if( ! password.equals("")) {
                    updateUserPassword = this.stm.executeUpdate("UPDATE `users` SET `password` = '"+ password +"' WHERE `userID` = '"+ uID +"'");
                }
                
                if(updateUserProfile > 0 || updateUserName > 0 || updateUserPassword > 0) {
                    this.updateTable();
                    
                    headerTitle.setText("Data user "+ nama +" berhasil diperbarui");
                    headerTitle.setVisible(true);

                    inputHP.setText("");
                    inputNama.setText("");
                    selectGrant.setSelectedIndex(0);
                    usernameField.setText("");
                    passwordField.setText("");

                    this.updateTable();
                    addBtn.setVisible(true);
                    delBtn.setVisible(false);
                    editBtn.setVisible(false);
                }
                else {
                    headerTitle.setText("Terjadi kesalahan saat memperbarui data. Silahkan ulangi kembali");
                    headerTitle.setVisible(true);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(datausers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void selectGrantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectGrantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectGrantActionPerformed

    private void delBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/deleteuser2.png"));
        delBtn.setIcon(b);
    }//GEN-LAST:event_delBtnMouseEntered

    private void delBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/deleteuser1.png"));
        delBtn.setIcon(b);
    }//GEN-LAST:event_delBtnMouseExited

    private void delBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/deleteuser1.png"));
        delBtn.setIcon(b);
    }//GEN-LAST:event_delBtnMousePressed

    private void delBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/deleteuser2.png"));
        delBtn.setIcon(b);
    }//GEN-LAST:event_delBtnMouseReleased

    private void editBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/edituser2.png"));
        editBtn.setIcon(b);
    }//GEN-LAST:event_editBtnMouseEntered

    private void editBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/edituser1.png"));
        editBtn.setIcon(b);
    }//GEN-LAST:event_editBtnMouseExited

    private void editBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/edituser1.png"));
        editBtn.setIcon(b);
    }//GEN-LAST:event_editBtnMousePressed

    private void editBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/edituser2.png"));
        editBtn.setIcon(b);
    }//GEN-LAST:event_editBtnMouseReleased

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/tambahuser2.png"));
        addBtn.setIcon(b); 
    }//GEN-LAST:event_addBtnMouseEntered

    private void addBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/tambahuser1.png"));
        addBtn.setIcon(b); 
    }//GEN-LAST:event_addBtnMouseExited

    private void addBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/tambahuser1.png"));
        addBtn.setIcon(b); 
    }//GEN-LAST:event_addBtnMousePressed

    private void addBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/tambahuser2.png"));
        addBtn.setIcon(b); 
    }//GEN-LAST:event_addBtnMouseReleased

    private void onsreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onsreenMousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_onsreenMousePressed

    private void onsreenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onsreenMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse,y-dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_onsreenMouseDragged

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void userbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/userbtn1.png"));
        userbtn.setIcon(b);
    }//GEN-LAST:event_userbtnMousePressed

    private void userbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/userbtn2.png"));
        userbtn.setIcon(b);
    }//GEN-LAST:event_userbtnMouseReleased

    private void userbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/userbtn1.png"));
        userbtn.setIcon(b);
    }//GEN-LAST:event_userbtnMouseExited

    private void userbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/userbtn2.png"));
        userbtn.setIcon(b);
    }//GEN-LAST:event_userbtnMouseEntered

    private void menubtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/menubtn1.png"));
        menubtn.setIcon(b);
    }//GEN-LAST:event_menubtnMousePressed

    private void menubtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/menubtn2.png"));
        menubtn.setIcon(b);
    }//GEN-LAST:event_menubtnMouseReleased

    private void menubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseClicked
        try {
            new menu().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menubtnMouseClicked

    private void menubtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/menubtn1.png"));
        menubtn.setIcon(b);
    }//GEN-LAST:event_menubtnMouseExited

    private void menubtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/menubtn2.png"));
        menubtn.setIcon(b);
    }//GEN-LAST:event_menubtnMouseEntered

    private void menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubtnActionPerformed

    }//GEN-LAST:event_menubtnActionPerformed

    private void pilihanbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanbtnMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/pilihanbtn1.png"));
        pilihanbtn.setIcon(b);
    }//GEN-LAST:event_pilihanbtnMousePressed

    private void pilihanbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanbtnMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/pilihanbtn2.png"));
        pilihanbtn.setIcon(b);
    }//GEN-LAST:event_pilihanbtnMouseReleased

    private void pilihanbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanbtnMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/pilihanbtn1.png"));
        pilihanbtn.setIcon(b);
    }//GEN-LAST:event_pilihanbtnMouseExited

    private void pilihanbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanbtnMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/pilihanbtn2.png"));
        pilihanbtn.setIcon(b);
    }//GEN-LAST:event_pilihanbtnMouseEntered

    private void userbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseClicked
        try {
            new datausers().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_userbtnMouseClicked

    private void pilihanbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilihanbtnMouseClicked
        try {
            new pilihan().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pilihanbtnMouseClicked

    private void statusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/status1.png"));
        status.setIcon(b);
    }//GEN-LAST:event_statusMousePressed

    private void statusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/status2.png"));
        status.setIcon(b);
    }//GEN-LAST:event_statusMouseReleased

    private void statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseClicked
        try {
            new daftarPesanan().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_statusMouseClicked

    private void statusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/status1.png"));
        status.setIcon(b);
    }//GEN-LAST:event_statusMouseExited

    private void statusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/status2.png"));
        status.setIcon(b);
    }//GEN-LAST:event_statusMouseEntered

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datausers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datausers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datausers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datausers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new datausers().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(datausers.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel editID;
    private javax.swing.JLabel editPanel;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JLabel hpMsg;
    private javax.swing.JTextField inputHP;
    private javax.swing.JTextField inputNama;
    private javax.swing.JScrollPane menuPanel;
    private javax.swing.JButton menubtn;
    private javax.swing.JLabel nameAlert;
    private javax.swing.JLabel onsreen;
    private javax.swing.JLabel passwordALert;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton pilihanbtn;
    private javax.swing.JComboBox selectGrant;
    private javax.swing.JButton status;
    private javax.swing.JTable userList;
    private javax.swing.JButton userbtn;
    private javax.swing.JLabel usernameAlert;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
